// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: books/v1/books.proto

package v1connect

import (
	v1 "booktest/api/books/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BooksServiceName is the fully-qualified name of the BooksService service.
	BooksServiceName = "books.v1.BooksService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BooksServiceBooksByTagsProcedure is the fully-qualified name of the BooksService's BooksByTags
	// RPC.
	BooksServiceBooksByTagsProcedure = "/books.v1.BooksService/BooksByTags"
	// BooksServiceBooksByTitleYearProcedure is the fully-qualified name of the BooksService's
	// BooksByTitleYear RPC.
	BooksServiceBooksByTitleYearProcedure = "/books.v1.BooksService/BooksByTitleYear"
	// BooksServiceCreateAuthorProcedure is the fully-qualified name of the BooksService's CreateAuthor
	// RPC.
	BooksServiceCreateAuthorProcedure = "/books.v1.BooksService/CreateAuthor"
	// BooksServiceCreateBookProcedure is the fully-qualified name of the BooksService's CreateBook RPC.
	BooksServiceCreateBookProcedure = "/books.v1.BooksService/CreateBook"
	// BooksServiceDeleteBookProcedure is the fully-qualified name of the BooksService's DeleteBook RPC.
	BooksServiceDeleteBookProcedure = "/books.v1.BooksService/DeleteBook"
	// BooksServiceGetAuthorProcedure is the fully-qualified name of the BooksService's GetAuthor RPC.
	BooksServiceGetAuthorProcedure = "/books.v1.BooksService/GetAuthor"
	// BooksServiceGetBookProcedure is the fully-qualified name of the BooksService's GetBook RPC.
	BooksServiceGetBookProcedure = "/books.v1.BooksService/GetBook"
	// BooksServiceUpdateBookProcedure is the fully-qualified name of the BooksService's UpdateBook RPC.
	BooksServiceUpdateBookProcedure = "/books.v1.BooksService/UpdateBook"
	// BooksServiceUpdateBookISBNProcedure is the fully-qualified name of the BooksService's
	// UpdateBookISBN RPC.
	BooksServiceUpdateBookISBNProcedure = "/books.v1.BooksService/UpdateBookISBN"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	booksServiceServiceDescriptor                = v1.File_books_v1_books_proto.Services().ByName("BooksService")
	booksServiceBooksByTagsMethodDescriptor      = booksServiceServiceDescriptor.Methods().ByName("BooksByTags")
	booksServiceBooksByTitleYearMethodDescriptor = booksServiceServiceDescriptor.Methods().ByName("BooksByTitleYear")
	booksServiceCreateAuthorMethodDescriptor     = booksServiceServiceDescriptor.Methods().ByName("CreateAuthor")
	booksServiceCreateBookMethodDescriptor       = booksServiceServiceDescriptor.Methods().ByName("CreateBook")
	booksServiceDeleteBookMethodDescriptor       = booksServiceServiceDescriptor.Methods().ByName("DeleteBook")
	booksServiceGetAuthorMethodDescriptor        = booksServiceServiceDescriptor.Methods().ByName("GetAuthor")
	booksServiceGetBookMethodDescriptor          = booksServiceServiceDescriptor.Methods().ByName("GetBook")
	booksServiceUpdateBookMethodDescriptor       = booksServiceServiceDescriptor.Methods().ByName("UpdateBook")
	booksServiceUpdateBookISBNMethodDescriptor   = booksServiceServiceDescriptor.Methods().ByName("UpdateBookISBN")
)

// BooksServiceClient is a client for the books.v1.BooksService service.
type BooksServiceClient interface {
	BooksByTags(context.Context, *connect.Request[v1.BooksByTagsRequest]) (*connect.Response[v1.BooksByTagsResponse], error)
	BooksByTitleYear(context.Context, *connect.Request[v1.BooksByTitleYearRequest]) (*connect.Response[v1.BooksByTitleYearResponse], error)
	CreateAuthor(context.Context, *connect.Request[v1.CreateAuthorRequest]) (*connect.Response[v1.CreateAuthorResponse], error)
	CreateBook(context.Context, *connect.Request[v1.CreateBookRequest]) (*connect.Response[v1.CreateBookResponse], error)
	DeleteBook(context.Context, *connect.Request[v1.DeleteBookRequest]) (*connect.Response[v1.DeleteBookResponse], error)
	GetAuthor(context.Context, *connect.Request[v1.GetAuthorRequest]) (*connect.Response[v1.GetAuthorResponse], error)
	GetBook(context.Context, *connect.Request[v1.GetBookRequest]) (*connect.Response[v1.GetBookResponse], error)
	UpdateBook(context.Context, *connect.Request[v1.UpdateBookRequest]) (*connect.Response[v1.UpdateBookResponse], error)
	UpdateBookISBN(context.Context, *connect.Request[v1.UpdateBookISBNRequest]) (*connect.Response[v1.UpdateBookISBNResponse], error)
}

// NewBooksServiceClient constructs a client for the books.v1.BooksService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBooksServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BooksServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &booksServiceClient{
		booksByTags: connect.NewClient[v1.BooksByTagsRequest, v1.BooksByTagsResponse](
			httpClient,
			baseURL+BooksServiceBooksByTagsProcedure,
			connect.WithSchema(booksServiceBooksByTagsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		booksByTitleYear: connect.NewClient[v1.BooksByTitleYearRequest, v1.BooksByTitleYearResponse](
			httpClient,
			baseURL+BooksServiceBooksByTitleYearProcedure,
			connect.WithSchema(booksServiceBooksByTitleYearMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createAuthor: connect.NewClient[v1.CreateAuthorRequest, v1.CreateAuthorResponse](
			httpClient,
			baseURL+BooksServiceCreateAuthorProcedure,
			connect.WithSchema(booksServiceCreateAuthorMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createBook: connect.NewClient[v1.CreateBookRequest, v1.CreateBookResponse](
			httpClient,
			baseURL+BooksServiceCreateBookProcedure,
			connect.WithSchema(booksServiceCreateBookMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteBook: connect.NewClient[v1.DeleteBookRequest, v1.DeleteBookResponse](
			httpClient,
			baseURL+BooksServiceDeleteBookProcedure,
			connect.WithSchema(booksServiceDeleteBookMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAuthor: connect.NewClient[v1.GetAuthorRequest, v1.GetAuthorResponse](
			httpClient,
			baseURL+BooksServiceGetAuthorProcedure,
			connect.WithSchema(booksServiceGetAuthorMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getBook: connect.NewClient[v1.GetBookRequest, v1.GetBookResponse](
			httpClient,
			baseURL+BooksServiceGetBookProcedure,
			connect.WithSchema(booksServiceGetBookMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateBook: connect.NewClient[v1.UpdateBookRequest, v1.UpdateBookResponse](
			httpClient,
			baseURL+BooksServiceUpdateBookProcedure,
			connect.WithSchema(booksServiceUpdateBookMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateBookISBN: connect.NewClient[v1.UpdateBookISBNRequest, v1.UpdateBookISBNResponse](
			httpClient,
			baseURL+BooksServiceUpdateBookISBNProcedure,
			connect.WithSchema(booksServiceUpdateBookISBNMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// booksServiceClient implements BooksServiceClient.
type booksServiceClient struct {
	booksByTags      *connect.Client[v1.BooksByTagsRequest, v1.BooksByTagsResponse]
	booksByTitleYear *connect.Client[v1.BooksByTitleYearRequest, v1.BooksByTitleYearResponse]
	createAuthor     *connect.Client[v1.CreateAuthorRequest, v1.CreateAuthorResponse]
	createBook       *connect.Client[v1.CreateBookRequest, v1.CreateBookResponse]
	deleteBook       *connect.Client[v1.DeleteBookRequest, v1.DeleteBookResponse]
	getAuthor        *connect.Client[v1.GetAuthorRequest, v1.GetAuthorResponse]
	getBook          *connect.Client[v1.GetBookRequest, v1.GetBookResponse]
	updateBook       *connect.Client[v1.UpdateBookRequest, v1.UpdateBookResponse]
	updateBookISBN   *connect.Client[v1.UpdateBookISBNRequest, v1.UpdateBookISBNResponse]
}

// BooksByTags calls books.v1.BooksService.BooksByTags.
func (c *booksServiceClient) BooksByTags(ctx context.Context, req *connect.Request[v1.BooksByTagsRequest]) (*connect.Response[v1.BooksByTagsResponse], error) {
	return c.booksByTags.CallUnary(ctx, req)
}

// BooksByTitleYear calls books.v1.BooksService.BooksByTitleYear.
func (c *booksServiceClient) BooksByTitleYear(ctx context.Context, req *connect.Request[v1.BooksByTitleYearRequest]) (*connect.Response[v1.BooksByTitleYearResponse], error) {
	return c.booksByTitleYear.CallUnary(ctx, req)
}

// CreateAuthor calls books.v1.BooksService.CreateAuthor.
func (c *booksServiceClient) CreateAuthor(ctx context.Context, req *connect.Request[v1.CreateAuthorRequest]) (*connect.Response[v1.CreateAuthorResponse], error) {
	return c.createAuthor.CallUnary(ctx, req)
}

// CreateBook calls books.v1.BooksService.CreateBook.
func (c *booksServiceClient) CreateBook(ctx context.Context, req *connect.Request[v1.CreateBookRequest]) (*connect.Response[v1.CreateBookResponse], error) {
	return c.createBook.CallUnary(ctx, req)
}

// DeleteBook calls books.v1.BooksService.DeleteBook.
func (c *booksServiceClient) DeleteBook(ctx context.Context, req *connect.Request[v1.DeleteBookRequest]) (*connect.Response[v1.DeleteBookResponse], error) {
	return c.deleteBook.CallUnary(ctx, req)
}

// GetAuthor calls books.v1.BooksService.GetAuthor.
func (c *booksServiceClient) GetAuthor(ctx context.Context, req *connect.Request[v1.GetAuthorRequest]) (*connect.Response[v1.GetAuthorResponse], error) {
	return c.getAuthor.CallUnary(ctx, req)
}

// GetBook calls books.v1.BooksService.GetBook.
func (c *booksServiceClient) GetBook(ctx context.Context, req *connect.Request[v1.GetBookRequest]) (*connect.Response[v1.GetBookResponse], error) {
	return c.getBook.CallUnary(ctx, req)
}

// UpdateBook calls books.v1.BooksService.UpdateBook.
func (c *booksServiceClient) UpdateBook(ctx context.Context, req *connect.Request[v1.UpdateBookRequest]) (*connect.Response[v1.UpdateBookResponse], error) {
	return c.updateBook.CallUnary(ctx, req)
}

// UpdateBookISBN calls books.v1.BooksService.UpdateBookISBN.
func (c *booksServiceClient) UpdateBookISBN(ctx context.Context, req *connect.Request[v1.UpdateBookISBNRequest]) (*connect.Response[v1.UpdateBookISBNResponse], error) {
	return c.updateBookISBN.CallUnary(ctx, req)
}

// BooksServiceHandler is an implementation of the books.v1.BooksService service.
type BooksServiceHandler interface {
	BooksByTags(context.Context, *connect.Request[v1.BooksByTagsRequest]) (*connect.Response[v1.BooksByTagsResponse], error)
	BooksByTitleYear(context.Context, *connect.Request[v1.BooksByTitleYearRequest]) (*connect.Response[v1.BooksByTitleYearResponse], error)
	CreateAuthor(context.Context, *connect.Request[v1.CreateAuthorRequest]) (*connect.Response[v1.CreateAuthorResponse], error)
	CreateBook(context.Context, *connect.Request[v1.CreateBookRequest]) (*connect.Response[v1.CreateBookResponse], error)
	DeleteBook(context.Context, *connect.Request[v1.DeleteBookRequest]) (*connect.Response[v1.DeleteBookResponse], error)
	GetAuthor(context.Context, *connect.Request[v1.GetAuthorRequest]) (*connect.Response[v1.GetAuthorResponse], error)
	GetBook(context.Context, *connect.Request[v1.GetBookRequest]) (*connect.Response[v1.GetBookResponse], error)
	UpdateBook(context.Context, *connect.Request[v1.UpdateBookRequest]) (*connect.Response[v1.UpdateBookResponse], error)
	UpdateBookISBN(context.Context, *connect.Request[v1.UpdateBookISBNRequest]) (*connect.Response[v1.UpdateBookISBNResponse], error)
}

// NewBooksServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBooksServiceHandler(svc BooksServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	booksServiceBooksByTagsHandler := connect.NewUnaryHandler(
		BooksServiceBooksByTagsProcedure,
		svc.BooksByTags,
		connect.WithSchema(booksServiceBooksByTagsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	booksServiceBooksByTitleYearHandler := connect.NewUnaryHandler(
		BooksServiceBooksByTitleYearProcedure,
		svc.BooksByTitleYear,
		connect.WithSchema(booksServiceBooksByTitleYearMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	booksServiceCreateAuthorHandler := connect.NewUnaryHandler(
		BooksServiceCreateAuthorProcedure,
		svc.CreateAuthor,
		connect.WithSchema(booksServiceCreateAuthorMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	booksServiceCreateBookHandler := connect.NewUnaryHandler(
		BooksServiceCreateBookProcedure,
		svc.CreateBook,
		connect.WithSchema(booksServiceCreateBookMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	booksServiceDeleteBookHandler := connect.NewUnaryHandler(
		BooksServiceDeleteBookProcedure,
		svc.DeleteBook,
		connect.WithSchema(booksServiceDeleteBookMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	booksServiceGetAuthorHandler := connect.NewUnaryHandler(
		BooksServiceGetAuthorProcedure,
		svc.GetAuthor,
		connect.WithSchema(booksServiceGetAuthorMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	booksServiceGetBookHandler := connect.NewUnaryHandler(
		BooksServiceGetBookProcedure,
		svc.GetBook,
		connect.WithSchema(booksServiceGetBookMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	booksServiceUpdateBookHandler := connect.NewUnaryHandler(
		BooksServiceUpdateBookProcedure,
		svc.UpdateBook,
		connect.WithSchema(booksServiceUpdateBookMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	booksServiceUpdateBookISBNHandler := connect.NewUnaryHandler(
		BooksServiceUpdateBookISBNProcedure,
		svc.UpdateBookISBN,
		connect.WithSchema(booksServiceUpdateBookISBNMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/books.v1.BooksService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BooksServiceBooksByTagsProcedure:
			booksServiceBooksByTagsHandler.ServeHTTP(w, r)
		case BooksServiceBooksByTitleYearProcedure:
			booksServiceBooksByTitleYearHandler.ServeHTTP(w, r)
		case BooksServiceCreateAuthorProcedure:
			booksServiceCreateAuthorHandler.ServeHTTP(w, r)
		case BooksServiceCreateBookProcedure:
			booksServiceCreateBookHandler.ServeHTTP(w, r)
		case BooksServiceDeleteBookProcedure:
			booksServiceDeleteBookHandler.ServeHTTP(w, r)
		case BooksServiceGetAuthorProcedure:
			booksServiceGetAuthorHandler.ServeHTTP(w, r)
		case BooksServiceGetBookProcedure:
			booksServiceGetBookHandler.ServeHTTP(w, r)
		case BooksServiceUpdateBookProcedure:
			booksServiceUpdateBookHandler.ServeHTTP(w, r)
		case BooksServiceUpdateBookISBNProcedure:
			booksServiceUpdateBookISBNHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBooksServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBooksServiceHandler struct{}

func (UnimplementedBooksServiceHandler) BooksByTags(context.Context, *connect.Request[v1.BooksByTagsRequest]) (*connect.Response[v1.BooksByTagsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.BooksByTags is not implemented"))
}

func (UnimplementedBooksServiceHandler) BooksByTitleYear(context.Context, *connect.Request[v1.BooksByTitleYearRequest]) (*connect.Response[v1.BooksByTitleYearResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.BooksByTitleYear is not implemented"))
}

func (UnimplementedBooksServiceHandler) CreateAuthor(context.Context, *connect.Request[v1.CreateAuthorRequest]) (*connect.Response[v1.CreateAuthorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.CreateAuthor is not implemented"))
}

func (UnimplementedBooksServiceHandler) CreateBook(context.Context, *connect.Request[v1.CreateBookRequest]) (*connect.Response[v1.CreateBookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.CreateBook is not implemented"))
}

func (UnimplementedBooksServiceHandler) DeleteBook(context.Context, *connect.Request[v1.DeleteBookRequest]) (*connect.Response[v1.DeleteBookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.DeleteBook is not implemented"))
}

func (UnimplementedBooksServiceHandler) GetAuthor(context.Context, *connect.Request[v1.GetAuthorRequest]) (*connect.Response[v1.GetAuthorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.GetAuthor is not implemented"))
}

func (UnimplementedBooksServiceHandler) GetBook(context.Context, *connect.Request[v1.GetBookRequest]) (*connect.Response[v1.GetBookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.GetBook is not implemented"))
}

func (UnimplementedBooksServiceHandler) UpdateBook(context.Context, *connect.Request[v1.UpdateBookRequest]) (*connect.Response[v1.UpdateBookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.UpdateBook is not implemented"))
}

func (UnimplementedBooksServiceHandler) UpdateBookISBN(context.Context, *connect.Request[v1.UpdateBookISBNRequest]) (*connect.Response[v1.UpdateBookISBNResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("books.v1.BooksService.UpdateBookISBN is not implemented"))
}
