// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: books/v1/books.proto

package v1connect

import (
	v1 "booktest/api/books/v1"
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// BooksServiceName is the fully-qualified name of the BooksService service.
	BooksServiceName = "books.v1.BooksService"
)

// BooksServiceClient is a client for the books.v1.BooksService service.
type BooksServiceClient interface {
	BooksByTags(context.Context, *connect_go.Request[v1.BooksByTagsRequest]) (*connect_go.Response[v1.BooksByTagsResponse], error)
	BooksByTitleYear(context.Context, *connect_go.Request[v1.BooksByTitleYearRequest]) (*connect_go.Response[v1.BooksByTitleYearResponse], error)
	CreateAuthor(context.Context, *connect_go.Request[v1.CreateAuthorRequest]) (*connect_go.Response[v1.CreateAuthorResponse], error)
	CreateBook(context.Context, *connect_go.Request[v1.CreateBookRequest]) (*connect_go.Response[v1.CreateBookResponse], error)
	DeleteBook(context.Context, *connect_go.Request[v1.DeleteBookRequest]) (*connect_go.Response[v1.DeleteBookResponse], error)
	GetAuthor(context.Context, *connect_go.Request[v1.GetAuthorRequest]) (*connect_go.Response[v1.GetAuthorResponse], error)
	GetBook(context.Context, *connect_go.Request[v1.GetBookRequest]) (*connect_go.Response[v1.GetBookResponse], error)
	UpdateBook(context.Context, *connect_go.Request[v1.UpdateBookRequest]) (*connect_go.Response[v1.UpdateBookResponse], error)
	UpdateBookISBN(context.Context, *connect_go.Request[v1.UpdateBookISBNRequest]) (*connect_go.Response[v1.UpdateBookISBNResponse], error)
}

// NewBooksServiceClient constructs a client for the books.v1.BooksService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBooksServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) BooksServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &booksServiceClient{
		booksByTags: connect_go.NewClient[v1.BooksByTagsRequest, v1.BooksByTagsResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/BooksByTags",
			opts...,
		),
		booksByTitleYear: connect_go.NewClient[v1.BooksByTitleYearRequest, v1.BooksByTitleYearResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/BooksByTitleYear",
			opts...,
		),
		createAuthor: connect_go.NewClient[v1.CreateAuthorRequest, v1.CreateAuthorResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/CreateAuthor",
			opts...,
		),
		createBook: connect_go.NewClient[v1.CreateBookRequest, v1.CreateBookResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/CreateBook",
			opts...,
		),
		deleteBook: connect_go.NewClient[v1.DeleteBookRequest, v1.DeleteBookResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/DeleteBook",
			opts...,
		),
		getAuthor: connect_go.NewClient[v1.GetAuthorRequest, v1.GetAuthorResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/GetAuthor",
			opts...,
		),
		getBook: connect_go.NewClient[v1.GetBookRequest, v1.GetBookResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/GetBook",
			opts...,
		),
		updateBook: connect_go.NewClient[v1.UpdateBookRequest, v1.UpdateBookResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/UpdateBook",
			opts...,
		),
		updateBookISBN: connect_go.NewClient[v1.UpdateBookISBNRequest, v1.UpdateBookISBNResponse](
			httpClient,
			baseURL+"/books.v1.BooksService/UpdateBookISBN",
			opts...,
		),
	}
}

// booksServiceClient implements BooksServiceClient.
type booksServiceClient struct {
	booksByTags      *connect_go.Client[v1.BooksByTagsRequest, v1.BooksByTagsResponse]
	booksByTitleYear *connect_go.Client[v1.BooksByTitleYearRequest, v1.BooksByTitleYearResponse]
	createAuthor     *connect_go.Client[v1.CreateAuthorRequest, v1.CreateAuthorResponse]
	createBook       *connect_go.Client[v1.CreateBookRequest, v1.CreateBookResponse]
	deleteBook       *connect_go.Client[v1.DeleteBookRequest, v1.DeleteBookResponse]
	getAuthor        *connect_go.Client[v1.GetAuthorRequest, v1.GetAuthorResponse]
	getBook          *connect_go.Client[v1.GetBookRequest, v1.GetBookResponse]
	updateBook       *connect_go.Client[v1.UpdateBookRequest, v1.UpdateBookResponse]
	updateBookISBN   *connect_go.Client[v1.UpdateBookISBNRequest, v1.UpdateBookISBNResponse]
}

// BooksByTags calls books.v1.BooksService.BooksByTags.
func (c *booksServiceClient) BooksByTags(ctx context.Context, req *connect_go.Request[v1.BooksByTagsRequest]) (*connect_go.Response[v1.BooksByTagsResponse], error) {
	return c.booksByTags.CallUnary(ctx, req)
}

// BooksByTitleYear calls books.v1.BooksService.BooksByTitleYear.
func (c *booksServiceClient) BooksByTitleYear(ctx context.Context, req *connect_go.Request[v1.BooksByTitleYearRequest]) (*connect_go.Response[v1.BooksByTitleYearResponse], error) {
	return c.booksByTitleYear.CallUnary(ctx, req)
}

// CreateAuthor calls books.v1.BooksService.CreateAuthor.
func (c *booksServiceClient) CreateAuthor(ctx context.Context, req *connect_go.Request[v1.CreateAuthorRequest]) (*connect_go.Response[v1.CreateAuthorResponse], error) {
	return c.createAuthor.CallUnary(ctx, req)
}

// CreateBook calls books.v1.BooksService.CreateBook.
func (c *booksServiceClient) CreateBook(ctx context.Context, req *connect_go.Request[v1.CreateBookRequest]) (*connect_go.Response[v1.CreateBookResponse], error) {
	return c.createBook.CallUnary(ctx, req)
}

// DeleteBook calls books.v1.BooksService.DeleteBook.
func (c *booksServiceClient) DeleteBook(ctx context.Context, req *connect_go.Request[v1.DeleteBookRequest]) (*connect_go.Response[v1.DeleteBookResponse], error) {
	return c.deleteBook.CallUnary(ctx, req)
}

// GetAuthor calls books.v1.BooksService.GetAuthor.
func (c *booksServiceClient) GetAuthor(ctx context.Context, req *connect_go.Request[v1.GetAuthorRequest]) (*connect_go.Response[v1.GetAuthorResponse], error) {
	return c.getAuthor.CallUnary(ctx, req)
}

// GetBook calls books.v1.BooksService.GetBook.
func (c *booksServiceClient) GetBook(ctx context.Context, req *connect_go.Request[v1.GetBookRequest]) (*connect_go.Response[v1.GetBookResponse], error) {
	return c.getBook.CallUnary(ctx, req)
}

// UpdateBook calls books.v1.BooksService.UpdateBook.
func (c *booksServiceClient) UpdateBook(ctx context.Context, req *connect_go.Request[v1.UpdateBookRequest]) (*connect_go.Response[v1.UpdateBookResponse], error) {
	return c.updateBook.CallUnary(ctx, req)
}

// UpdateBookISBN calls books.v1.BooksService.UpdateBookISBN.
func (c *booksServiceClient) UpdateBookISBN(ctx context.Context, req *connect_go.Request[v1.UpdateBookISBNRequest]) (*connect_go.Response[v1.UpdateBookISBNResponse], error) {
	return c.updateBookISBN.CallUnary(ctx, req)
}

// BooksServiceHandler is an implementation of the books.v1.BooksService service.
type BooksServiceHandler interface {
	BooksByTags(context.Context, *connect_go.Request[v1.BooksByTagsRequest]) (*connect_go.Response[v1.BooksByTagsResponse], error)
	BooksByTitleYear(context.Context, *connect_go.Request[v1.BooksByTitleYearRequest]) (*connect_go.Response[v1.BooksByTitleYearResponse], error)
	CreateAuthor(context.Context, *connect_go.Request[v1.CreateAuthorRequest]) (*connect_go.Response[v1.CreateAuthorResponse], error)
	CreateBook(context.Context, *connect_go.Request[v1.CreateBookRequest]) (*connect_go.Response[v1.CreateBookResponse], error)
	DeleteBook(context.Context, *connect_go.Request[v1.DeleteBookRequest]) (*connect_go.Response[v1.DeleteBookResponse], error)
	GetAuthor(context.Context, *connect_go.Request[v1.GetAuthorRequest]) (*connect_go.Response[v1.GetAuthorResponse], error)
	GetBook(context.Context, *connect_go.Request[v1.GetBookRequest]) (*connect_go.Response[v1.GetBookResponse], error)
	UpdateBook(context.Context, *connect_go.Request[v1.UpdateBookRequest]) (*connect_go.Response[v1.UpdateBookResponse], error)
	UpdateBookISBN(context.Context, *connect_go.Request[v1.UpdateBookISBNRequest]) (*connect_go.Response[v1.UpdateBookISBNResponse], error)
}

// NewBooksServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBooksServiceHandler(svc BooksServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/books.v1.BooksService/BooksByTags", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/BooksByTags",
		svc.BooksByTags,
		opts...,
	))
	mux.Handle("/books.v1.BooksService/BooksByTitleYear", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/BooksByTitleYear",
		svc.BooksByTitleYear,
		opts...,
	))
	mux.Handle("/books.v1.BooksService/CreateAuthor", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/CreateAuthor",
		svc.CreateAuthor,
		opts...,
	))
	mux.Handle("/books.v1.BooksService/CreateBook", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/CreateBook",
		svc.CreateBook,
		opts...,
	))
	mux.Handle("/books.v1.BooksService/DeleteBook", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/DeleteBook",
		svc.DeleteBook,
		opts...,
	))
	mux.Handle("/books.v1.BooksService/GetAuthor", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/GetAuthor",
		svc.GetAuthor,
		opts...,
	))
	mux.Handle("/books.v1.BooksService/GetBook", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/GetBook",
		svc.GetBook,
		opts...,
	))
	mux.Handle("/books.v1.BooksService/UpdateBook", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/UpdateBook",
		svc.UpdateBook,
		opts...,
	))
	mux.Handle("/books.v1.BooksService/UpdateBookISBN", connect_go.NewUnaryHandler(
		"/books.v1.BooksService/UpdateBookISBN",
		svc.UpdateBookISBN,
		opts...,
	))
	return "/books.v1.BooksService/", mux
}

// UnimplementedBooksServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBooksServiceHandler struct{}

func (UnimplementedBooksServiceHandler) BooksByTags(context.Context, *connect_go.Request[v1.BooksByTagsRequest]) (*connect_go.Response[v1.BooksByTagsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.BooksByTags is not implemented"))
}

func (UnimplementedBooksServiceHandler) BooksByTitleYear(context.Context, *connect_go.Request[v1.BooksByTitleYearRequest]) (*connect_go.Response[v1.BooksByTitleYearResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.BooksByTitleYear is not implemented"))
}

func (UnimplementedBooksServiceHandler) CreateAuthor(context.Context, *connect_go.Request[v1.CreateAuthorRequest]) (*connect_go.Response[v1.CreateAuthorResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.CreateAuthor is not implemented"))
}

func (UnimplementedBooksServiceHandler) CreateBook(context.Context, *connect_go.Request[v1.CreateBookRequest]) (*connect_go.Response[v1.CreateBookResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.CreateBook is not implemented"))
}

func (UnimplementedBooksServiceHandler) DeleteBook(context.Context, *connect_go.Request[v1.DeleteBookRequest]) (*connect_go.Response[v1.DeleteBookResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.DeleteBook is not implemented"))
}

func (UnimplementedBooksServiceHandler) GetAuthor(context.Context, *connect_go.Request[v1.GetAuthorRequest]) (*connect_go.Response[v1.GetAuthorResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.GetAuthor is not implemented"))
}

func (UnimplementedBooksServiceHandler) GetBook(context.Context, *connect_go.Request[v1.GetBookRequest]) (*connect_go.Response[v1.GetBookResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.GetBook is not implemented"))
}

func (UnimplementedBooksServiceHandler) UpdateBook(context.Context, *connect_go.Request[v1.UpdateBookRequest]) (*connect_go.Response[v1.UpdateBookResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.UpdateBook is not implemented"))
}

func (UnimplementedBooksServiceHandler) UpdateBookISBN(context.Context, *connect_go.Request[v1.UpdateBookISBNRequest]) (*connect_go.Response[v1.UpdateBookISBNResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("books.v1.BooksService.UpdateBookISBN is not implemented"))
}
