// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect).

package pguuid

import (
	"uuidcheck/api/pguuid/v1/v1connect"
)

// NewService is a constructor of a v1.PguuidServiceHandler implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier *Queries) v1connect.PguuidServiceHandler {
	return &Service{querier: querier}
}
