// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect). DO NOT EDIT.

package authors

import (
	"context"
	"database/sql"
	"log/slog"

	"connectrpc.com/connect"

	pb "authors/api/authors/v1"
	"authors/api/authors/v1/v1connect"
)

type Service struct {
	v1connect.UnimplementedAuthorsServiceHandler
	querier *Queries
}

func (s *Service) CreateAuthor(ctx context.Context, req *connect.Request[pb.CreateAuthorRequest]) (*connect.Response[pb.CreateAuthorResponse], error) {
	var arg createAuthorParams
	arg.Name = req.Msg.GetName()
	if v := req.Msg.GetBio(); v != nil {
		arg.Bio = sql.NullString{Valid: true, String: v.Value}
	}

	result, err := s.querier.createAuthor(ctx, arg)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "createAuthor")
		return nil, err
	}
	return connect.NewResponse(&pb.CreateAuthorResponse{Value: toExecResult(result)}), nil
}

func (s *Service) DeleteAuthor(ctx context.Context, req *connect.Request[pb.DeleteAuthorRequest]) (*connect.Response[pb.DeleteAuthorResponse], error) {
	id := req.Msg.GetId()

	err := s.querier.deleteAuthor(ctx, id)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "deleteAuthor")
		return nil, err
	}
	return connect.NewResponse(&pb.DeleteAuthorResponse{}), nil
}

func (s *Service) GetAuthor(ctx context.Context, req *connect.Request[pb.GetAuthorRequest]) (*connect.Response[pb.GetAuthorResponse], error) {
	id := req.Msg.GetId()

	result, err := s.querier.getAuthor(ctx, id)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "getAuthor")
		return nil, err
	}
	return connect.NewResponse(&pb.GetAuthorResponse{Author: toAuthor(result)}), nil
}

func (s *Service) ListAuthors(ctx context.Context, req *connect.Request[pb.ListAuthorsRequest]) (*connect.Response[pb.ListAuthorsResponse], error) {

	result, err := s.querier.listAuthors(ctx)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "listAuthors")
		return nil, err
	}
	res := new(pb.ListAuthorsResponse)
	for _, r := range result {
		res.List = append(res.List, toAuthor(r))
	}
	return connect.NewResponse(res), nil
}
