// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect). DO NOT EDIT.

package main

import (
	"net/http"

	grpcreflect "github.com/bufbuild/connect-grpcreflect-go"
	"github.com/jackc/pgx/v5/pgxpool"

	authors_v1connect "authors/api/authors/v1/v1connect"
	authors_app "authors/internal/authors"
)

func registerHandlers(mux *http.ServeMux, db *pgxpool.Pool) {
	authorsService := authors_app.NewService(authors_app.New(), db)
	authorsPath, authorsHandler := authors_v1connect.NewAuthorsServiceHandler(authorsService)
	mux.Handle(authorsPath, authorsHandler)

	reflector := grpcreflect.NewStaticReflector(
		authors_v1connect.AuthorsServiceName,
	)
	mux.Handle(grpcreflect.NewHandlerV1(reflector))
	mux.Handle(grpcreflect.NewHandlerV1Alpha(reflector))
}
