// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect).

package books

import (
	"booktest/api/books/v1/v1connect"
)

// NewService is a constructor of a v1.BooksServiceHandler implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier *Queries) v1connect.BooksServiceHandler {
	return &Service{querier: querier}
}
