// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect).

package books

import (
	"go.uber.org/zap"

	"booktest/api/books/v1/v1connect"
)

// NewService is a constructor of a v1.BooksServiceHandler implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(logger *zap.Logger, querier *Queries) v1connect.BooksServiceHandler {
	return &Service{logger: logger, querier: querier}
}
