// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect). DO NOT EDIT.

package main

import (
	"database/sql"
	"net/http"

	grpcreflect "github.com/bufbuild/connect-grpcreflect-go"

	books_v1connect "booktest/api/books/v1/v1connect"
	books_app "booktest/internal/books"
)

func registerHandlers(mux *http.ServeMux, db *sql.DB) {
	booksService := books_app.NewService(books_app.New(db))
	booksPath, booksHandler := books_v1connect.NewBooksServiceHandler(booksService)
	mux.Handle(booksPath, booksHandler)

	reflector := grpcreflect.NewStaticReflector(
		books_v1connect.BooksServiceName,
	)
	mux.Handle(grpcreflect.NewHandlerV1(reflector))
	mux.Handle(grpcreflect.NewHandlerV1Alpha(reflector))
}
