// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect).

package googleuuid

import (
	"uuidcheck/api/googleuuid/v1/v1connect"
)

// NewService is a constructor of a v1.GoogleuuidServiceHandler implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier *Queries) v1connect.GoogleuuidServiceHandler {
	return &Service{querier: querier}
}
