// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect).

package main

import (
	"context"
	"database/sql"
	_ "embed"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"runtime"
	"strings"
	"syscall"
	"time"

	"connectrpc.com/connect"
	"github.com/flowchartsman/swaggerui"
	"github.com/litesql/go-ha"
	"go.uber.org/automaxprocs/maxprocs"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	// database driver
	_ "github.com/litesql/go-sqlite-ha"

	"authors/internal/server/litestream"
)

//go:generate sqlc-connect -m authors -migration-path sql/migrations -litestream -append

const (
	serviceName    = "authors"
	forwardTimeout = 10 * time.Second
)

var (
	dbURL          string
	port           int
	replicationURL string
	node           string
	leaderRedirect bool
	staticLeader   string
	advertiseAddr  string
	natsAsyncPub   bool
	natsConfig     string
	natsPort       int
	natsURL        string
	cdcID          string
	clusterSize    int

	//go:embed api/apidocs.swagger.json
	openAPISpec []byte
)

func main() {
	var dev bool
	flag.StringVar(&dbURL, "db", "", "The Database connection URL")
	flag.IntVar(&port, "port", 5000, "The server port")
	flag.BoolVar(&dev, "dev", false, "Set logger to development mode")
	flag.StringVar(&replicationURL, "replication", "", "S3 replication URL")
	flag.StringVar(&node, "node", "", "Node name identify (for database replication)")
	flag.StringVar(&cdcID, "cdc-id", "", "CDC ID for replication (defaults to database filename)")
	flag.IntVar(&clusterSize, "cluster-size", 1, "Cluster size (for leader election)")
	flag.StringVar(&natsConfig, "nats-config", "", "Embedded NATS configuration file path (overrides other NATS configs)")
	flag.IntVar(&natsPort, "nats-port", 0, "Embedded NATS port for database replication")
	flag.StringVar(&natsURL, "nats-url", "", "External NATS URL connect for database replication. Ex: nats://host:4222")
	flag.BoolVar(&natsAsyncPub, "nats-async-pub", false, "Async publishes to NATS")
	flag.BoolVar(&leaderRedirect, "leader-redirect", false, "Redirect POST/PUT/DELETE/PATCH requests to Leader")
	flag.StringVar(&staticLeader, "leader-target", "", "Leader static target endoint")
	flag.StringVar(&advertiseAddr, "advertise-addr", "", "Advertise address (ex: http://localhost:5000)")
	flag.Parse()

	hostname, _ := os.Hostname()
	if hostname == "" {
		hostname = "localhost"
	}
	if advertiseAddr == "" {
		advertiseAddr = fmt.Sprintf("http://%s:%d", hostname, port)
	}

	if !strings.Contains(dbURL, "?") {
		dbURL += "?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)&_pragma=synchronous=NORMAL&_txlock=immediate"
	}
	dbURL += "&autoStart=false"
	if node != "" {
		dbURL += fmt.Sprintf("&name=%s", node)
	}
	if natsConfig != "" {
		dbURL += fmt.Sprintf("&natsConfigFile=%s", natsConfig)
	}
	if natsPort > 0 {
		dbURL += fmt.Sprintf("&natsPort=%d", natsPort)
	}
	if natsURL != "" {
		dbURL += fmt.Sprintf("&replicationURL=%s", natsURL)
	}
	if natsAsyncPub {
		dbURL += "&asyncPublisher=true"
	}
	if cdcID != "" {
		dbURL += fmt.Sprintf("&cdcID=%s", cdcID)
	}
	if clusterSize > 0 {
		dbURL += fmt.Sprintf("&clusterSize=%d", clusterSize)
	}
	if leaderRedirect {
		if staticLeader != "" {
			dbURL += fmt.Sprintf("&leaderProvider=static:%s", staticLeader)
		} else {
			dbURL += fmt.Sprintf("&leaderProvider=dynamic:%s", advertiseAddr)
		}
	}

	dbURL = "file:" + strings.TrimPrefix(dbURL, "file:")

	initLogger(dev)

	if err := run(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		slog.Error("server error", "error", err)
		os.Exit(1)
	}
}

func run() error {
	_, err := maxprocs.Set()
	if err != nil {
		slog.Warn("startup", "error", err)
	}
	slog.Info("startup", "GOMAXPROCS", runtime.GOMAXPROCS(0))
	defer ha.Shutdown()

	db, err := sql.Open("sqlite-ha", dbURL)
	if err != nil {
		return err
	}
	defer db.Close()

	if replicationURL != "" {
		slog.Info("replication", "url", replicationURL)
		lsdb, err := litestream.Replicate(context.Background(), dbURL, replicationURL)
		if err != nil {
			return fmt.Errorf("init replication error: %w", err)
		}
		defer lsdb.Close(context.Background())
	}
	if err := ensureSchema(db); err != nil {
		return fmt.Errorf("migration error: %w", err)
	}

	connector, ok := ha.LookupConnector(dbURL)
	if ok {
		err := connector.Start(db)
		if err != nil {
			return fmt.Errorf("failed to start connector: %w", err)
		}
	} else {
		return fmt.Errorf("connector not found")
	}

	if leaderRedirect {
		slog.Info("waiting for a leader")
		<-connector.LeaderProvider().Ready()
		slog.Info("leader elected", "target", connector.LeaderProvider().RedirectTarget())
	}

	mux := http.NewServeMux()
	var interceptors []connect.Interceptor

	registerHandlers(mux, db, interceptors)
	mux.Handle("/swagger/", http.StripPrefix("/swagger", swaggerui.Handler(openAPISpec)))

	var handler http.Handler = mux
	if leaderRedirect {
		handler = connector.ForwardToLeader(forwardTimeout, "POST", "PUT", "PATCH", "DELETE")(handler)
		handler = connector.ConsistentReader(forwardTimeout, "GET")(handler)
	}
	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: h2c.NewHandler(handler, &http2.Server{}),
		// Please, configure timeouts!
	}

	done := make(chan os.Signal, 1)
	signal.Notify(done, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		sig := <-done
		slog.Warn("signal detected...", "signal", sig)
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()
		server.Shutdown(ctx)
	}()
	slog.Info("Listening...", "port", port)
	return server.ListenAndServe()
}

func initLogger(dev bool) {
	var handler slog.Handler
	opts := slog.HandlerOptions{
		AddSource: true,
	}
	switch {
	case dev:
		handler = slog.NewTextHandler(os.Stderr, &opts)
	default:
		handler = slog.NewJSONHandler(os.Stderr, &opts)
	}

	logger := slog.New(handler)
	slog.SetDefault(logger)
}
