// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect). DO NOT EDIT.

package main

import (
	"database/sql"
	"net/http"

	grpcreflect "github.com/bufbuild/connect-grpcreflect-go"
	"go.uber.org/zap"

	authors_v1connect "authors/api/authors/v1/v1connect"
	authors_app "authors/internal/authors"
)

func registerHandlers(mux *http.ServeMux, logger *zap.Logger, db *sql.DB) {
	authorsService := authors_app.NewService(logger, authors_app.New(db))
	authorsPath, authorsHandler := authors_v1connect.NewAuthorsServiceHandler(authorsService)
	mux.Handle(authorsPath, authorsHandler)

	reflector := grpcreflect.NewStaticReflector(
		authors_v1connect.AuthorsServiceName,
	)
	mux.Handle(grpcreflect.NewHandlerV1(reflector))
	mux.Handle(grpcreflect.NewHandlerV1Alpha(reflector))
}
